### ISSUE TITLE
Placement of Next/Prev Buttons

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/ca11y#22]
![screen shot 2015-12-23 at 5 04 48 pm](https://cloud.githubusercontent.com/assets/1037707/11985875/512260b8-a997-11e5-9d36-865eb272433d.png)

Because the next and previous buttons are in the lower left corner, when switching between months that have a different number of week rows, the next and previous buttons shift up and down which makes it frustrating when navigating them with the mouse (clicking on next/prev repeatedly.)

**Comment by greypants** [comment]
yep. Let's `position: absolute` from the top instead.

**Comment by jacksonfox** [comment]
:+1: 

Was just playing with this (looks really nice!) but kept closing the date picker on accident because the buttons are moving when transitioning between long and short months.

Example: http://take.ms/Lhkri
