### ISSUE TITLE
Invalid Input Values

### ISSUE THREAD

**Issue by cwmanning** [vigetlabs/ca11y#25]
Should the date input default to showing an error state when the input value is not in the `YYYY-MM-DD` format? I manually entered a value instead of using the picker here:

<img width="276" alt="screen shot 2016-01-11 at 11 26 38 am" src="https://cloud.githubusercontent.com/assets/1019830/12239339/3b608a2a-b856-11e5-95ce-b68ceb7e0d58.png">

https://html.spec.whatwg.org/multipage/infrastructure.html#valid-date-string

**Comment by solomonhawk** [comment]
After discussing with @greypants, we will opt to leave input validation to userland code and instead set Ca11y to a "no date selected" state whenever there is invalid data coming from the input.

**Comment by greypants** [comment]
@solomonhawk did you implement the "no date selected", or is that outstanding?
